app:
  greeting: "Hello, world (from application.yml in config-repo)"

message: "From application.yml in config-repo"

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
